# Generated by Django 4.2.7 on 2026-02-07 18:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, help_text='JWT ID claim', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('endpoint_accessed', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jwt_access_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('distance', 'Distance-based Alert'), ('hazard', 'Hazardous Asteroid Alert'), ('velocity', 'High Velocity Alert'), ('all', 'All Asteroids')], default='distance', max_length=20)),
                ('min_distance_km', models.FloatField(default=10000000, help_text='Alert only for asteroids closer than this (km)', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_distance_km', models.FloatField(default=100000000, help_text='Alert only for asteroids within this distance (km)', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_velocity_kmps', models.FloatField(default=0, help_text='Alert for asteroids faster than this (km/s)', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_days_notice', models.IntegerField(default=1, help_text='Alert this many days before approach', validators=[django.core.validators.MinValueValidator(0)])),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('dashboard', 'Dashboard Notification'), ('both', 'Both Email and Dashboard')], default='both', max_length=20)),
                ('hazard_only', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasa_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('diameter_min', models.FloatField(blank=True, null=True)),
                ('diameter_max', models.FloatField(blank=True, null=True)),
                ('absolute_magnitude', models.FloatField(blank=True, null=True)),
                ('is_potentially_hazardous', models.BooleanField(db_index=True, default=False)),
                ('nasa_url', models.URLField(blank=True, null=True)),
                ('orbital_period', models.FloatField(blank=True, null=True)),
                ('semi_major_axis', models.FloatField(blank=True, null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_potentially_hazardous', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CloseApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach_date', models.DateTimeField(db_index=True)),
                ('miss_distance_km', models.FloatField()),
                ('miss_distance_miles', models.FloatField(blank=True, null=True)),
                ('miss_distance_lunar', models.FloatField(blank=True, null=True)),
                ('relative_velocity_kmps', models.FloatField()),
                ('relative_velocity_kmph', models.FloatField(blank=True, null=True)),
                ('relative_velocity_mph', models.FloatField(blank=True, null=True)),
                ('orbiting_body', models.CharField(default='Earth', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_approaches', to='tracker.asteroid')),
            ],
            options={
                'ordering': ['approach_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(default='alert', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('close_approach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.closeapproach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_location', models.CharField(blank=True, max_length=255)),
                ('login_count', models.IntegerField(default=0)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('account_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('receive_marketing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserAsteroidWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_since', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.asteroid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_asteroids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=500, unique=True)),
                ('jti', models.CharField(db_index=True, help_text='JWT ID claim', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_blacklisted', models.BooleanField(db_index=True, default=False)),
                ('blacklisted_at', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, help_text='User agent or device info', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jwt_refresh_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('delivery_method', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('refresh_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracker.refreshtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_login_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='asteroid',
            index=models.Index(fields=['is_potentially_hazardous'], name='tracker_ast_is_pote_e15b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='asteroid',
            index=models.Index(fields=['name'], name='tracker_ast_name_6e9456_idx'),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='refresh_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='tracker.refreshtoken'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userasteroidwatch',
            unique_together={('user', 'asteroid')},
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'is_blacklisted'], name='jwt_refresh_user_id_40935d_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='jwt_refresh_expires_c470a4_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['jti'], name='jwt_refresh_jti_a2916e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='tracker_not_user_id_a89c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='tracker_not_schedul_0cd00c_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'is_active'], name='user_login__user_id_05aeeb_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['login_time'], name='user_login__login_t_538932_idx'),
        ),
        migrations.AddIndex(
            model_name='closeapproach',
            index=models.Index(fields=['approach_date'], name='tracker_clo_approac_6971dd_idx'),
        ),
        migrations.AddIndex(
            model_name='closeapproach',
            index=models.Index(fields=['asteroid', 'approach_date'], name='tracker_clo_asteroi_8fbfcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='closeapproach',
            unique_together={('asteroid', 'approach_date')},
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['user', 'expires_at'], name='jwt_access__user_id_e47e49_idx'),
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['jti'], name='jwt_access__jti_89c9c8_idx'),
        ),
    ]
